# Linear Regression
### 회귀분석 모형

다음 특징 변수 들을 이용하여 테스트 데이터에 예상되는 주택 가격을 도출 하시오.

예측 값과 실제 값의 차이 (오차율)의 합을 평균 낸 점수로 평가한다.

In [2]:
# 데이터 로드
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np

df = pd.read_csv('./extrafiles/house_price.csv')
df

       housing_age  income  bedrooms  households     rooms  house_value
0               23  6.7770  0.141112    2.442244  8.103960       500000
1               49  6.0199  0.160984    2.726688  5.752412       500000
2               35  5.1155  0.249061    1.902676  3.888078       500000
3               32  4.7109  0.231383    1.913669  4.508393       500000
4               21  4.5625  0.255583    3.092664  4.667954       500000
...            ...     ...       ...         ...       ...          ...
17684           34  2.3013  0.214583    2.748299  4.897959        26600
17685           33  2.6750  0.246622    3.428571  4.698413        22500
17686           39  2.3667  0.340771    1.876812  3.572464        17500
17687           19  2.1000  0.386107    2.987805  3.774390        14999
17688           16  1.6607  0.286275    2.236842  6.710526        14999

[17689 rows x 6 columns]